server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5 

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nagarjuna-guntu/config-repo		
          default-label: main
          timeout: 5
          clone-on-start: true #clone the repo on strat instead at first request served
          force-pull: true	#fresh copy is pulled whenever the local copy is corrupted, and any local changes are discarded.			 
info: 
  system: Polar Bookshop
    
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, configprops, env, health, heapdump, info, loggers, mappings, metrics
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true     
logging:
  pattern:
    correlation: "%clr([${spring.application.name:},%X{traceId:-},%X{spanId:-}]){yellow} "
  include-application-name: false 